import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from '@/app/components/Header'
const roboto = Roboto({
  subsets:["latin"],
  weight: ['400', '700']

});

export const metadata: Metadata = {
  title: "SupportTrack",
  description: "Generated by Steblovskiy Anton",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-white dark:bg-gray-800`} >
        <Header />
        {children}
      </body>
    </html>
  );
}
